# Generated by Django 4.2.4 on 2023-11-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('hab_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_personas', models.IntegerField()),
                ('tamaño', models.FloatField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('adultos', models.IntegerField()),
                ('niños', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_serv', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('Clientes_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_has_Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservas_id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.reservas')),
                ('Servicios_id_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas_has_Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habitaciones_hab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.habitaciones')),
                ('Reservas_id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.reservas')),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='Usuarios_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios'),
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titular', models.CharField(max_length=150)),
                ('ccv', models.CharField(max_length=3)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('Clientes_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clientes')),
                ('Usuarios_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones_has_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habitaciones_hab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.habitaciones')),
                ('Servicios_id_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.servicios')),
            ],
        ),
    ]
