# Generated by Django 4.2.4 on 2023-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='rol',
            field=models.CharField(default='Administrador', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(default='Cliente', editable=False, max_length=255),
        ),
    ]
