# Generated by Django 4.2.4 on 2023-11-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_administradores_rol_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
