# Generated by Django 4.2.4 on 2023-11-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_administradores_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='precio',
        ),
    ]
