# Generated by Django 4.2.4 on 2023-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_habitaciones_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
