# Generated by Django 4.2.4 on 2023-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_habitaciones_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='precio_reserva',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='precio_servicio',
            field=models.IntegerField(null=True),
        ),
    ]
