# Generated by Django 4.2.4 on 2023-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_reservas_precio_reserva_servicios_precio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
