# Generated by Django 4.2.4 on 2023-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_habitaciones_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
