# Generated by Django 4.2.4 on 2023-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_reservas_usuarios_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_salida',
            field=models.DateField(),
        ),
    ]
