# Generated by Django 4.2.7 on 2023-11-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_reservas_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones_has_servicios',
            name='Habitaciones_hab_id',
        ),
        migrations.AddField(
            model_name='habitaciones_has_servicios',
            name='Reservas_id_reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.reservas'),
        ),
        migrations.AlterField(
            model_name='habitaciones_has_servicios',
            name='Servicios_id_serv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.servicios'),
        ),
    ]
