# Generated by Django 4.2.7 on 2023-11-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remove_habitaciones_has_servicios_habitaciones_hab_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.habitaciones'),
        ),
    ]
