# Generated by Django 4.2.7 on 2023-11-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_reservas_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='habitacion',
        ),
    ]
