# Generated by Django 4.2.7 on 2023-11-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_remove_reservas_habitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=20)),
                ('titular_tarjeta', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('ccv', models.CharField(max_length=4)),
                ('mes_ano', models.CharField(max_length=7)),
            ],
        ),
    ]
